version: "3.8"
services:
  booking-api:
    image: booking-api
    build: ./backend
    container_name: booking-api
    init: true
    networks:
      - frontend
    ports:
      - "3000:3000"
  booking-client:
    image: booking-client
    build: ./frontend
    container_name: booking-client
    init: true
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - frontend
    ports:
      - "5174:5174"
networks:
  frontend: